apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
  labels:
    app: simple-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: python-server
        image: python:3.9-slim
        command: ["python", "-m", "http.server", "8000"]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-app-service
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
