apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-app
  labels:
    app: go-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-app
  template:
    metadata:
      labels:
        app: go-hello-app
    spec:
      containers:
      - name: go-hello-container
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=Hello from Go App deployed by Argo CD!"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-service
spec:
  selector:
    app: go-hello-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
